#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Straub.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SJS_NCAAM")]
	public partial class ORMDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ORMDataContext() : 
				base(global::Straub.Data.Properties.Settings.Default.SJS_NCAAMConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ORMDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ORMDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ORMDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ORMDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_Schedule> tbl_Schedules
		{
			get
			{
				return this.GetTable<tbl_Schedule>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NcaamScheduleCollection")]
		public ISingleResult<tbl_Schedule> NcaamScheduleCollection([global::System.Data.Linq.Mapping.ParameterAttribute(Name="VariableString", DbType="VarChar(MAX)")] string variableString)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), variableString);
			return ((ISingleResult<tbl_Schedule>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="RawStats.tbl_Schedule")]
	public partial class tbl_Schedule
	{
		
		private System.Nullable<double> _Season;
		
		private string _TeamId;
		
		private System.Nullable<double> _Gno;
		
		private System.Nullable<System.DateTime> _GameDate;
		
		private string _GameID;
		
		private string _GameTime;
		
		private string _Network;
		
		private string _GameType;
		
		private string _Loc;
		
		private string _OppId;
		
		private string _F11;
		
		private string _WL;
		
		private System.Nullable<double> _TmScore;
		
		private System.Nullable<double> _OppScore;
		
		private string _OT;
		
		private string _Arena;
		
		private System.Nullable<System.DateTime> _GameDateTime;
		
		private System.Nullable<double> _AwayTeamAP;
		
		private System.Nullable<double> _AwayTeamCoach;
		
		private string _AwayTeamId;
		
		private string _AwayTeam;
		
		private string _AwayConf;
		
		private System.Nullable<double> _HomeTeamAP;
		
		private System.Nullable<double> _HomeTeamCoach;
		
		private string _HomeTeamId;
		
		private string _HomeTeam;
		
		private string _HomeConf;
		
		private string _Winner;
		
		private System.Nullable<double> _WinScore;
		
		private System.Nullable<double> _LoseScore;
		
		private string _Favor;
		
		private System.Nullable<double> _Spread;
		
		private System.Nullable<double> _OverUnder;
		
		public tbl_Schedule()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Season", DbType="Float")]
		public System.Nullable<double> Season
		{
			get
			{
				return this._Season;
			}
			set
			{
				if ((this._Season != value))
				{
					this._Season = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamId", DbType="NVarChar(255)")]
		public string TeamId
		{
			get
			{
				return this._TeamId;
			}
			set
			{
				if ((this._TeamId != value))
				{
					this._TeamId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gno", DbType="Float")]
		public System.Nullable<double> Gno
		{
			get
			{
				return this._Gno;
			}
			set
			{
				if ((this._Gno != value))
				{
					this._Gno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GameDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> GameDate
		{
			get
			{
				return this._GameDate;
			}
			set
			{
				if ((this._GameDate != value))
				{
					this._GameDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GameID", DbType="NVarChar(255)")]
		public string GameID
		{
			get
			{
				return this._GameID;
			}
			set
			{
				if ((this._GameID != value))
				{
					this._GameID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GameTime", DbType="NVarChar(255)")]
		public string GameTime
		{
			get
			{
				return this._GameTime;
			}
			set
			{
				if ((this._GameTime != value))
				{
					this._GameTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Network", DbType="NVarChar(255)")]
		public string Network
		{
			get
			{
				return this._Network;
			}
			set
			{
				if ((this._Network != value))
				{
					this._Network = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GameType", DbType="NVarChar(255)")]
		public string GameType
		{
			get
			{
				return this._GameType;
			}
			set
			{
				if ((this._GameType != value))
				{
					this._GameType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loc", DbType="NVarChar(255)")]
		public string Loc
		{
			get
			{
				return this._Loc;
			}
			set
			{
				if ((this._Loc != value))
				{
					this._Loc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OppId", DbType="NVarChar(255)")]
		public string OppId
		{
			get
			{
				return this._OppId;
			}
			set
			{
				if ((this._OppId != value))
				{
					this._OppId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F11", DbType="NVarChar(255)")]
		public string Opponent
		{
			get
			{
				return this._F11;
			}
			set
			{
				if ((this._F11 != value))
				{
					this._F11 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WL", DbType="NVarChar(255)")]
		public string WL
		{
			get
			{
				return this._WL;
			}
			set
			{
				if ((this._WL != value))
				{
					this._WL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TmScore", DbType="Float")]
		public System.Nullable<double> TmScore
		{
			get
			{
				return this._TmScore;
			}
			set
			{
				if ((this._TmScore != value))
				{
					this._TmScore = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OppScore", DbType="Float")]
		public System.Nullable<double> OppScore
		{
			get
			{
				return this._OppScore;
			}
			set
			{
				if ((this._OppScore != value))
				{
					this._OppScore = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OT", DbType="NVarChar(255)")]
		public string OT
		{
			get
			{
				return this._OT;
			}
			set
			{
				if ((this._OT != value))
				{
					this._OT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Arena", DbType="NVarChar(255)")]
		public string Arena
		{
			get
			{
				return this._Arena;
			}
			set
			{
				if ((this._Arena != value))
				{
					this._Arena = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GameDateTime")]
		public System.Nullable<System.DateTime> GameDateTime
		{
			get
			{
				return this._GameDateTime;
			}
			set
			{
				if ((this._GameDateTime != value))
				{
					this._GameDateTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AwayTeamAP")]
		public System.Nullable<double> AwayTeamAP
		{
			get
			{
				return this._AwayTeamAP;
			}
			set
			{
				if ((this._AwayTeamAP != value))
				{
					this._AwayTeamAP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AwayTeamCoach")]
		public System.Nullable<double> AwayTeamCoach
		{
			get
			{
				return this._AwayTeamCoach;
			}
			set
			{
				if ((this._AwayTeamCoach != value))
				{
					this._AwayTeamCoach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AwayTeamId")]
		public string AwayTeamId
		{
			get
			{
				return this._AwayTeamId;
			}
			set
			{
				if ((this._AwayTeamId != value))
				{
					this._AwayTeamId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AwayTeam")]
		public string AwayTeam
		{
			get
			{
				return this._AwayTeam;
			}
			set
			{
				if ((this._AwayTeam != value))
				{
					this._AwayTeam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AwayConf")]
		public string AwayConf
		{
			get
			{
				return this._AwayConf;
			}
			set
			{
				if ((this._AwayConf != value))
				{
					this._AwayConf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HomeTeamAP")]
		public System.Nullable<double> HomeTeamAP
		{
			get
			{
				return this._HomeTeamAP;
			}
			set
			{
				if ((this._HomeTeamAP != value))
				{
					this._HomeTeamAP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HomeTeamCoach")]
		public System.Nullable<double> HomeTeamCoach
		{
			get
			{
				return this._HomeTeamCoach;
			}
			set
			{
				if ((this._HomeTeamCoach != value))
				{
					this._HomeTeamCoach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HomeTeamId")]
		public string HomeTeamId
		{
			get
			{
				return this._HomeTeamId;
			}
			set
			{
				if ((this._HomeTeamId != value))
				{
					this._HomeTeamId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HomeTeam")]
		public string HomeTeam
		{
			get
			{
				return this._HomeTeam;
			}
			set
			{
				if ((this._HomeTeam != value))
				{
					this._HomeTeam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HomeConf")]
		public string HomeConf
		{
			get
			{
				return this._HomeConf;
			}
			set
			{
				if ((this._HomeConf != value))
				{
					this._HomeConf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Winner")]
		public string Winner
		{
			get
			{
				return this._Winner;
			}
			set
			{
				if ((this._Winner != value))
				{
					this._Winner = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WinScore")]
		public System.Nullable<double> WinScore
		{
			get
			{
				return this._WinScore;
			}
			set
			{
				if ((this._WinScore != value))
				{
					this._WinScore = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoseScore")]
		public System.Nullable<double> LoseScore
		{
			get
			{
				return this._LoseScore;
			}
			set
			{
				if ((this._LoseScore != value))
				{
					this._LoseScore = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Favor", Storage="_Favor")]
		public string Favorite
		{
			get
			{
				return this._Favor;
			}
			set
			{
				if ((this._Favor != value))
				{
					this._Favor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Spread")]
		public System.Nullable<double> Spread
		{
			get
			{
				return this._Spread;
			}
			set
			{
				if ((this._Spread != value))
				{
					this._Spread = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OverUnder")]
		public System.Nullable<double> OverUnder
		{
			get
			{
				return this._OverUnder;
			}
			set
			{
				if ((this._OverUnder != value))
				{
					this._OverUnder = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
